-- 02_seed.sql — выполнять ПОСЛЕ 01_setup.sql. Повторный запуск ничего не перезаписывает (on conflict do nothing).
begin;
insert into public.tablo_categories (id,name,sort_order) values
('cat-mandatory','Обязательные программы обучения',0),
('cat-professions','Программы обучения по профессиям',1),
('cat-hse','Обучение по программам HSE',2)
on conflict (id) do nothing;
insert into public.tablo_courses (id,title,category_id,url,sort_order) values
('c-001','«Общие требования к перевозке опасных грузов автомобильным транспортом» 10ч','cat-mandatory','https://my.qgrnd.kz/~RK2x0',0),
('c-002','Безопасность работ в ЭУ для эл.технол. персонала 10ч','cat-mandatory','https://my.qgrnd.kz/~Z4ill',1),
('c-003','Безопасность работ в ЭУ для эл.технол. персонала 24ч','cat-mandatory','https://my.qgrnd.kz/~723fg',2),
('c-004','БиОТ 24ч','cat-mandatory','https://my.qgrnd.kz/~pm61W',3),
('c-005','БиОТ 40ч','cat-mandatory','https://my.qgrnd.kz/~TngBr',4),
('c-006','БиОТ 72ч','cat-mandatory','https://my.qgrnd.kz/~aWvML',5),
('c-007','ГОР 24ч','cat-mandatory','https://my.qgrnd.kz/~HM5Wx',6),
('c-008','ГПМ (надзор) 24, 40ч','cat-mandatory','https://my.qgrnd.kz/~LjY0R',7),
('c-009','ГПМ (производство) 10ч','cat-mandatory','https://my.qgrnd.kz/~Pi5LN',8),
('c-010','ГПМ (производство) 24, 40ч','cat-mandatory','https://my.qgrnd.kz/~dV8Et',9),
('c-011','ГПМ (содержание) 24, 40ч','cat-mandatory','https://my.qgrnd.kz/~6BR1P',10),
('c-012','ЛВЖиГЖ 10ч','cat-mandatory','https://my.qgrnd.kz/~RBxGw',11),
('c-013','Метанол и одорант 10ч','cat-mandatory','https://my.qgrnd.kz/~fDIkQ',12),
('c-014','Метанол и одорант 24 ч','cat-mandatory','https://my.qgrnd.kz/~nIb71',13),
('c-015','Оказание первой помощи 10ч','cat-mandatory','https://my.qgrnd.kz/~K1gXe',14),
('c-016','Оператор КУ 10ч','cat-mandatory','https://my.qgrnd.kz/~5q4u1',15),
('c-017','Основы электробезопасности 10ч','cat-mandatory','https://my.qgrnd.kz/~j9ON1',16),
('c-018','ПБ 10ч','cat-mandatory','https://my.qgrnd.kz/~KCdt8',17),
('c-019','ПБ 40ч','cat-mandatory','https://my.qgrnd.kz/~xNoNL',18),
('c-020','Прекурсоры 10ч','cat-mandatory','https://my.qgrnd.kz/~MDBgS',19),
('c-021','Прекурсоры 24ч','cat-mandatory','https://my.qgrnd.kz/~JYSUb',20),
('c-022','ПТМ для ответственных 12ч','cat-mandatory','https://my.qgrnd.kz/~2e5Z4',21),
('c-023','ПТМ для рабочих 12ч','cat-mandatory','https://my.qgrnd.kz/~pz16C',22),
('c-024','ПТМ для руководителей 8ч','cat-mandatory','https://my.qgrnd.kz/~3DJ2G',23),
('c-025','Работа на высоте 30ч','cat-mandatory','https://my.qgrnd.kz/~TWEq9',24),
('c-026','СВД 24ч','cat-mandatory','https://my.qgrnd.kz/~FEfRn',25),
('c-027','СДЯВ 10ч','cat-mandatory','https://my.qgrnd.kz/~lQ44t',26),
('c-028','Стропальщики 10ч','cat-mandatory','https://my.qgrnd.kz/~r5aKI',27),
('c-029','Тех.инспектора 10ч','cat-mandatory','https://my.qgrnd.kz/~Jucwe',28),
('c-030','Хим.лаборатория 10ч','cat-mandatory','https://my.qgrnd.kz/~6LEZn',29),
('c-031','Эл.безопасность (до и выше 1000В) 40ч. (доп)','cat-mandatory','https://my.qgrnd.kz/~j1RW2',30),
('c-032','Аккумуляторщик 40ч','cat-professions','https://my.qgrnd.kz/~YT6iF',31),
('c-033','Бурильщик, Пом.бур. 40ч','cat-professions','https://my.qgrnd.kz/~XInd2',32),
('c-034','Изолировщик трубопроводов от коррозии 36ч','cat-professions','https://my.qgrnd.kz/~JNTAK',33),
('c-035','Машинист ДКС','cat-professions','https://my.qgrnd.kz/~Zb1W3',34),
('c-036','Машинист мостового крана, управляемого с кабины 40 ч','cat-professions','https://my.qgrnd.kz/~OvJrq',35),
('c-037','Машинист ТК 40ч','cat-professions','https://my.qgrnd.kz/~4S3pE',36),
('c-038','Монтер по ЗПТотК 40ч','cat-professions','https://my.qgrnd.kz/~EYcbe',37),
('c-039','Оператор ГРС 40ч','cat-professions','https://my.qgrnd.kz/~uyK7M',38),
('c-040','Оператор крана управляемого с пола 32ч','cat-professions','https://my.qgrnd.kz/~wFjmI',39),
('c-041','Оператор КУ 40ч','cat-professions','https://my.qgrnd.kz/~BqxbG',40),
('c-042','Оператор по ДНиГ 36 ч','cat-professions','https://my.qgrnd.kz/~NQld2',41),
('c-043','Оператор по ИС 40ч','cat-professions','https://my.qgrnd.kz/~pbqGw',42),
('c-044','Приборист 40ч','cat-professions','https://my.qgrnd.kz/~WszGm',43),
('c-045','Слесарь АВР 40ч','cat-professions','https://my.qgrnd.kz/~hPf0K',44),
('c-046','Слесарь по КИПиА 40ч','cat-professions','https://my.qgrnd.kz/~4OVyN',45),
('c-047','Слесарь по ремонту ТУ 40ч','cat-professions','https://my.qgrnd.kz/~JEE0G',46),
('c-048','Слесарь по ЭиРПГ 40ч','cat-professions','https://my.qgrnd.kz/~kTgPu',47),
('c-049','Слесарь-ремонтник службы ЭВС 40ч','cat-professions','https://my.qgrnd.kz/~2gFXB',48),
('c-050','Стропальщики 40ч','cat-professions','https://my.qgrnd.kz/~V42e1',49),
('c-051','Трубопроводчик линейный 40ч','cat-professions','https://my.qgrnd.kz/~w3bd7',50),
('c-052','Электромонтер по ремонту ВЛ ЭП 40ч','cat-professions','https://my.qgrnd.kz/~FUYTt',51),
('c-053','Электромонтер по РиОЭО 40ч','cat-professions','https://my.qgrnd.kz/~TqKCF',52),
('c-054','IOSH Managing Safely','cat-hse','https://my.qgrnd.kz/~bi0Hq',53),
('c-055','IOSH Working Safely','cat-hse','https://my.qgrnd.kz/~j14O7',54),
('c-056','Vision Zero (Нулевой травматизм)','cat-hse','https://my.qgrnd.kz/~V6sM8',55),
('c-057','Вайб-кодинг и AI-инструменты в корпоративной среде 1 ч','cat-hse','https://my.qgrnd.kz/~57a5Z',56),
('c-058','Культура безопасности труда 24ч','cat-hse','https://my.qgrnd.kz/~6WWAI',57),
('c-059','ПАБ 6ч','cat-hse','https://my.qgrnd.kz/~LkS6K',58),
('c-060','Расследование происшествий в соответствии с ВНД 16 ч','cat-hse','https://my.qgrnd.kz/~J3gqu',59)
on conflict (id) do nothing;
insert into public.tablo_settings (key,value) values ('survey','{"title": "Оценка удовлетворенности слушателей", "url": "https://docs.google.com/forms/d/e/1FAIpQLSftiDhA2JCpPOJ0dIRw_hN7geRymEkDOWM1pNKah1q2guQ7zQ/viewform?usp=dialog"}'::jsonb)
on conflict (key) do nothing;
commit;
-- Проверка: select (select count(*) from tablo_categories) c, (select count(*) from tablo_courses) k; -- ожидается 3 и 60